# Generated by Django 4.1.5 on 2023-01-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_blog_borrower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='borrower',
            new_name='owner',
        ),
    ]
