# Generated by Django 4.1.5 on 2023-01-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_alter_avatar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='image',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='user',
        ),
        migrations.AddField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
